# Generated by Django 5.2.4 on 2025-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_paid_at_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
