# Generated by Django 5.2.4 on 2025-10-02 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
        ('payments', '0003_alter_payment_status_alter_payment_track_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='zibal', max_length=100, verbose_name='درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
