# Generated by Django 5.2.4 on 2025-10-05 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_paid_at_alter_order_shipping_address_and_more'),
        ('payments', '0004_alter_payment_amount_alter_payment_gateway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='zibal', max_length=100, verbose_name='Payment gateway'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Raw response'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='TrackId'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
