# Generated by Django 5.2.4 on 2025-07-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id'], 'verbose_name': 'بازخورد', 'verbose_name_plural': 'بازخورد ها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'علاقه مندی', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'عکس محصول', 'verbose_name_plural': 'عکس محصولات'},
        ),
    ]
