# Generated by Django 5.2.4 on 2025-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_like_unique_together_like_unique_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
