# Generated by Django 5.2.4 on 2025-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_feedback_description_alter_feedback_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='هابازدید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='هابازدید'),
        ),
    ]
