# Generated by Django 5.2.4 on 2025-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_visit_count_alter_product_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='بازدید ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='بازدید ها'),
        ),
    ]
