# Generated by Django 5.2.4 on 2025-07-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'عنوان ویژگی',
                'verbose_name_plural': ' عنوان ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی محصول',
                'verbose_name_plural': 'مقادیر ویژگی های محصول',
            },
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'مورد علاقه', 'verbose_name_plural': 'مورد علاقه ها'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='feedback',
            name='unique_user_product_feedback',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category', verbose_name='عنوان گروه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to='product.product'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='عکس رسمی'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='product.featurename', verbose_name='عنوان ویژگی'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='product.product', verbose_name='محصول'),
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.AddConstraint(
            model_name='featurevalue',
            constraint=models.UniqueConstraint(fields=('product', 'feature', 'value'), name='unique_product_feature_value'),
        ),
    ]
