# Generated by Django 5.2.4 on 2025-08-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_featurename_featurevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-visit_count'], 'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-visit_count'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
