# Generated by Django 5.2.4 on 2025-09-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_feedback_product_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'ordering': ['-id'], 'verbose_name': 'مقدار ویژگی محصول', 'verbose_name_plural': 'مقادیر ویژگی های محصول'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-rating'], 'verbose_name': 'بازخورد', 'verbose_name_plural': 'بازخورد ها'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-id']},
        ),
    ]
