# Generated by Django 5.2.4 on 2025-09-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_featurevalue_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-visit_count', '-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
