# Generated by Django 5.2.4 on 2025-09-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='product.featurename', verbose_name='عنوان ویژگی'),
        ),
        migrations.AlterField(
            model_name='featurevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature_values', to='product.product', verbose_name='محصول'),
        ),
    ]
