# Generated by Django 5.2.4 on 2025-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, max_length=100, verbose_name='برند'),
        ),
    ]
