# Generated by Django 5.2.4 on 2025-09-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='featurevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='product.product', verbose_name='محصول'),
        ),
    ]
