# Generated by Django 5.2.4 on 2025-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='عکس رسی', null=True, upload_to='products/', verbose_name='عکس اصلی'),
        ),
    ]
