# Generated by Django 5.2.4 on 2025-09-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurename',
            options={'verbose_name': 'اسم ویژگی', 'verbose_name_plural': ' اسم ویژگی ها'},
        ),
    ]
