# Generated by Django 5.2.4 on 2025-09-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_featurename_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='عکس رسمی'),
        ),
    ]
