# Generated by Django 5.2.4 on 2025-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_like_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurename',
            options={'verbose_name': 'عنوان ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterField(
            model_name='featurename',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی'),
        ),
    ]
