# Generated by Django 5.2.4 on 2025-09-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_featurename_options_alter_featurename_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'ordering': ['-id'], 'verbose_name': 'مقدار ویژگی ', 'verbose_name_plural': 'مقادیر ویژگی ها'},
        ),
    ]
