# Generated by Django 5.2.4 on 2025-09-15 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('end_date', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, related_name='category_discounts', to='product.category')),
                ('products', models.ManyToManyField(blank=True, related_name='product_discounts', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
