# Generated by Django 5.2.4 on 2025-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_alter_discount_options_alter_discount_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_discounts', to='product.category', verbose_name='گروه ها'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(verbose_name='تایخ انقضا'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_discounts', to='product.product', verbose_name='محصولات'),
        ),
    ]
