# Generated by Django 5.2.4 on 2025-09-15 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_discount_categories_alter_discount_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='products',
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='product.product', verbose_name='محصولات'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='discount',
            name='categories',
        ),
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='product.category', verbose_name='گروه ها'),
            preserve_default=False,
        ),
    ]
