# Generated by Django 5.2.4 on 2025-09-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_remove_discount_products_discount_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='product.category', verbose_name='گروه ها'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='product.product', verbose_name='محصولات'),
        ),
    ]
