# Generated by Django 5.2.4 on 2025-09-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_discount_categories_alter_discount_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='categories',
            new_name='category',
        ),
    ]
