# Generated by Django 5.2.4 on 2025-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_rename_categories_discount_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('title', 'brand'), name='unique_title'),
        ),
    ]
