# Generated by Django 5.2.4 on 2025-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_product_unique_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('title', 'parent'), name='unique_category_per_parent'),
        ),
    ]
