# Generated by Django 5.2.4 on 2025-09-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_category_unique_category_per_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'عکس ها', 'verbose_name_plural': 'عکس ها'},
        ),
    ]
