# Generated by Django 5.2.4 on 2025-09-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='product.product', verbose_name='محصولات'),
        ),
    ]
