# Generated by Django 5.2.4 on 2025-09-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_remove_like_unique_user_product_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='product.category', verbose_name='گروه ها'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='product.product', verbose_name='محصولات'),
        ),
    ]
