# Generated by Django 5.2.4 on 2025-10-07 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_category_parent_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=70, message='Max percent value 70')], verbose_name='Percent'),
        ),
    ]
