# Generated by Django 5.2.4 on 2025-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
