# Generated by Django 5.2.4 on 2025-08-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'اردر', 'verbose_name_plural': 'اردرها'},
        ),
    ]
