# Generated by Django 5.2.4 on 2025-08-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقدار سفارش', 'verbose_name_plural': 'مقادیر سفارش'},
        ),
    ]
