# Generated by Django 5.2.4 on 2025-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('shipped', 'SHIPPED')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
