# Generated by Django 5.2.4 on 2025-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_order_shipping_address_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(null=True, verbose_name='آدرس تحویل'),
        ),
    ]
