# Generated by Django 5.2.4 on 2025-08-30 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_total_amount_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='آدرس تحویل'),
            preserve_default=False,
        ),
    ]
