# Generated by Django 5.2.4 on 2025-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of total when order created', max_digits=10),
        ),
    ]
