# Generated by Django 5.2.4 on 2025-09-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_cartitem_product_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
    ]
