# Generated by Django 5.2.4 on 2025-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_remove_cartitem_unique_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of the total price at checkout time', max_digits=10, verbose_name='مبلغ کل'),
        ),
    ]
