# Generated by Django 5.2.4 on 2025-09-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
