# Generated by Django 5.2.4 on 2025-09-20 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0049_remove_like_unique_user_product_like_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('shipped', 'SHIPPED')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('shipping_address', models.TextField(verbose_name='آدرس تحویل')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of the total price at checkout time', max_digits=15, verbose_name='مبلغ کل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='مقدار')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_order_items', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار سفارش',
                'verbose_name_plural': 'مقادیر سفارش',
                'ordering': ['-created_at'],
            },
        ),
    ]
