# Generated by Django 5.2.4 on 2025-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
