# Generated by Django 5.2.4 on 2025-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_pending_order_per_user',
        ),
    ]
